/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VpAudioPlayer: typeof import('el-admin-components')['VpAudioPlayer']
    VpAvatarList: typeof import('el-admin-components')['VpAvatarList']
    VpChangeLocale: typeof import('el-admin-components')['VpChangeLocale']
    VpDarkModeToggle: typeof import('el-admin-components')['VpDarkModeToggle']
    VpDescription: typeof import('el-admin-components')['VpDescription']
    VpEditor: typeof import('el-admin-components')['VpEditor']
    VpForm: typeof import('el-admin-components')['VpForm']
    VpHeader: typeof import('el-admin-components')['VpHeader']
    VpHeaderTabs: typeof import('el-admin-components')['VpHeaderTabs']
    VpIconList: typeof import('el-admin-components')['VpIconList']
    VpIconPicker: typeof import('el-admin-components')['VpIconPicker']
    VpMenu: typeof import('el-admin-components')['VpMenu']
    VpNotice: typeof import('el-admin-components')['VpNotice']
    VpNotification: typeof import('el-admin-components')['VpNotification']
    VpTable: typeof import('el-admin-components')['VpTable']
    VpVideoPlayer: typeof import('el-admin-components')['VpVideoPlayer']
  }
  export interface ComponentCustomProperties {
    vCopy: typeof import('el-admin-components')['VpDirectiveCopy']
    vDebounce: typeof import('el-admin-components')['VpDirectiveDebounce']
    vDraggable: typeof import('el-admin-components')['VpDirectiveDraggable']
    vFlash: typeof import('el-admin-components')['VpDirectiveFlash']
    vLongPress: typeof import('el-admin-components')['VpDirectiveLongPress']
    vScrollText: typeof import('el-admin-components')['VpDirectiveScrollText']
    vThrottle: typeof import('el-admin-components')['VpDirectiveThrottle']
    vWaterMarker: typeof import('el-admin-components')['VpDirectiveWaterMarker']
  }
}
